name: Compile Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gchat_mbox_extractor
            asset_name: gchat_mbox_extractor-linux-amd64
          - os: windows-latest
            artifact_name: gchat_mbox_extractor.exe
            asset_name: gchat_mbox_extractor-windows-amd64.exe
          - os: macos-latest
            artifact_name: gchat_mbox_extractor
            asset_name: gchat_mbox_extractor-macos-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
