name: Compile Release
on:
  push:
    tags:
      - 'v*'
      
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gchat_mbox_extractor
            asset_name: gchat_mbox_extractor-linux-amd64
          - os: windows-latest
            artifact_name: gchat_mbox_extractor.exe
            asset_name: gchat_mbox_extractor-windows-amd64.exe
          - os: macos-latest
            artifact_name: gchat_mbox_extractor
            asset_name: gchat_mbox_extractor-macos-amd64

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cargo rustc --release -- -C link-args="/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: cargo build --release

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: cargo build --release

      - name: Rename artifact
        run: |
          mv target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}
